// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::testBoardCANMotor1;
std::shared_ptr<frc::Ultrasonic> RobotMap::testBoardUltra;
std::shared_ptr<WPI_TalonSRX> RobotMap::testBoardCANMotor2;
std::shared_ptr<WPI_TalonSRX> RobotMap::testBoardCANMotor3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    testBoardCANMotor1.reset(new WPI_TalonSRX(0));
    
    
    testBoardUltra.reset(new frc::Ultrasonic(0, 1));
    lw->AddSensor("TestBoard", "Ultra", testBoardUltra);
    
    testBoardCANMotor2.reset(new WPI_TalonSRX(1));
    
    
    testBoardCANMotor3.reset(new WPI_TalonSRX(2));
    
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
